version: '3.8'

services:
  # (Database)
  db:
    image: postgres:15
    container_name: purrvision_postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: purrvision_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d purrvision_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  # The Task Queue (Redis)
  redis:
    image: redis:7
    container_name: purrvision_redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 30s
      retries: 50

volumes:
  postgres_data: