apiVersion: v1
kind: Secret
metadata:
  name: {{ include "woocommerce.fullname" . }}-auth
  labels:
    {{- include "woocommerce.labels" . | nindent 4 }}
type: Opaque
data:
  # Encodes the passwords defined in values.yaml
  wordpress-password: {{ .Values.mariadb.auth.password | b64enc | quote }}
  mariadb-root-password: {{ .Values.mariadb.auth.rootPassword | b64enc | quote }}
  mariadb-replication-password: {{ .Values.mariadb.auth.password | b64enc | quote }}
  wordpress-admin-password: {{ .Values.wordpress.admin.password | b64enc | quote }}